PACKAGE_NAME="reform2_lpc"
PACKAGE_VERSION="@@VERSION@@"
MAKE[0]="make KERNEL_DIR=/lib/modules/${kernelver}/build all"
BUILT_MODULE_NAME[0]="reform2_lpc"
DEST_MODULE_LOCATION[0]="/extra"
AUTOINSTALL="yes"
